### ISSUE TITLE
Following examples in Ch. 4 for "MyToolbar" results in error

### ISSUE THREAD

**Issue by Stokestack** [PacktPublishing/Mastering-Qt-5#11]
Since Apple Books doesn't offer a proper page number, I can only refer to the part of Chapter 4 where you start working with QML files and you create one called MyToolbar.qml. The section starts with "Let's build a new MyToolbar componenet by creating a new file called MyToolbar.qml"

You then try to use it in main.qml, but that doesn't work. The result at runtime is:
2019-06-19 02:13:09.983412-0700 gallery-mobile[41325:10201510] qrc:/main.qml:17 MyToolbar is not a type

**Comment by GuillaumeLazar** [comment]
Can't reproduce.

**Comment by Stokestack** [comment]
Thanks for checking it out. Will re-file if I can repro in the future.

**Comment by GuillaumeLazar** [comment]
If you want try. Go on the second edition repository and download the source code. The first edition is deprecated and many bugs have been fixed in the second edition. https://github.com/PacktPublishing/Mastering-Qt-5-Second-Editon
