### ISSUE TITLE
Chapter 4 & 5 code asserts when adding a picture

### ISSUE THREAD

**Issue by bigguiness** [PacktPublishing/Mastering-Qt-5#12]
I tried going through Chapter 5 myself and kept getting an assert when adding a picture:

Query OK: "INSERT INTO pictures (album_id, url) VALUES (:album_id, :url)"
ASSERT: "proxyIndex.model() == this" in file itemmodels\qidentityproxymodel.cpp, line 259

I then found this repo so I tried the Chapter 5 code from the repo. Same result.

The debug call path shows that the last executed line in the code  is:

```
void AlbumWidget::addPictures() {
    ...
        ui->thumbnailListView->setCurrentIndex(lastModelIndex);

```

The failing assert is in:

`QModelIndex QIdentityProxyModel::mapToSource(const QModelIndex& proxyIndex)`

Any ideas why?

**Comment by GuillaumeLazar** [comment]
It's remember me something. I guess we already fixed it on GitHub repository of the second edition. Can you check if this PR help you? https://github.com/PacktPublishing/Mastering-Qt-5-Second-Editon/pull/1

**Comment by GuillaumeLazar** [comment]
I also applied the PR on this repository. You can check it here: https://github.com/PacktPublishing/Mastering-Qt-5/pull/10/commits/bd85b9177f6f29dee70684d954e3b0956a4d4a7d

**Comment by JosephA-packt** [comment]
I hope that you have got your answer  
@bigguiness
