### ISSUE TITLE
German localised version

### ISSUE THREAD

**Issue by ShalokShalom** [PacktPublishing/Mastering-Qt-5#2]
Is there a German version as well? 

Maybe from a similar book?

There is so much room for this market..
Qt5 books in German.

**Comment by GuillaumeLazar** [comment]
Sorry our book "Mastering Qt 5" exists only in english. There is no plan for a german version.

However, we tried to write this book in a clear english, you are may be able to read it. Check the content with the amazon preview feature "look inside" : [https://www.amazon.com/Mastering-Qt-5-Guillaume-Lazar/dp/1786467127/](https://www.amazon.com/Mastering-Qt-5-Guillaume-Lazar/dp/1786467127/)

**Comment by ShalokShalom** [comment]
Thanks a lot
