### ISSUE TITLE
ch07-image-filter compile problem

### ISSUE THREAD

**Issue by davidedifilippo** [PacktPublishing/Mastering-Qt-5#3]
the project in chapter 7 doesn't copy shared object in QT designer plugin directory. I have copied it by hand. It works

**Comment by davidedifilippo** [comment]
QT creator 4.3.1
QT 5.9.1

**Comment by GuillaumeLazar** [comment]
What is your OS? A `make install` should do the job for you. Maybe a path issue in the [filter-plugin-designer.pro](https://github.com/PacktPublishing/Mastering-Qt-5/blob/master/Chapter_07/filter-plugin-designer/filter-plugin-designer.pro)
