### ISSUE TITLE
Repository doesn't match book

### ISSUE THREAD

**Issue by nsparks86** [PacktPublishing/Mastering-Qt-5#6]
Book has the repository as "https://github.com/PacktPublishing/masteringqt5/". One of the two should be updated.

**Comment by GuillaumeLazar** [comment]
It's an errata of the book, the repository "PacktPublishing/masteringqt5" doesn't exist. 
The correct repository URL is https://github.com/PacktPublishing/Mastering-Qt-5

You can submit the errata to packt from this page:
https://www.packtpub.com/books/content/errata
