### ISSUE TITLE
Errata in  Character5

### ISSUE THREAD

**Issue by xqdd** [PacktPublishing/Mastering-Qt-5#7]
in ch05-gallery-mobile , the  PictureImageProvider.cpp file

Does here must be "key" rather than  “pictureSize”？
( Forgive my  poor English and Grammar)

![image](https://user-images.githubusercontent.com/20871761/32475425-a3de0826-c3ac-11e7-8de8-1e71b795ac67.png)

**Comment by xqdd** [comment]
Sorry,I didn't read the README.md file

**Comment by GuillaumeLazar** [comment]
Hello,

Yes you're right, you must use the key.

As you saw after, it's described in the [README.md](https://github.com/PacktPublishing/Mastering-Qt-5/blob/master/README.md) file in [the Errata section Chapter 5](https://github.com/PacktPublishing/Mastering-Qt-5/blob/master/README.md#chapter-5).

Please also note that the GitHub source code is already updated, check the file [PictureImageProvider.cpp](https://github.com/PacktPublishing/Mastering-Qt-5/blob/master/Chapter_05/gallery-mobile/PictureImageProvider.cpp)
