### ISSUE TITLE
ch06-snake with Qt 5.10.0 fail to start

### ISSUE THREAD

**Issue by elpaso** [PacktPublishing/Mastering-Qt-5#9]
qml: Start game...
QQmlComponent: Component is not ready
qrc:/factory.js:32: TypeError: Cannot call method 'setParent' of null

**Comment by GuillaumeLazar** [comment]
Hi,

I fixed it 5 days ago in 06e3493a. Checkout or[ download the last version](https://github.com/PacktPublishing/Mastering-Qt-5/archive/master.zip) of the sources. 
I'm using Qt 5.10.1, you should also update your Qt version.
